source("../R/job_helpers.R")

ctx <- kflow_stage_start("report")
kflow_write_manifest(ctx$input_dir, file.path(ctx$out_dir, "input-manifest.csv"))

registry_files <- list.files(ctx$input_dir, pattern = "^model-registry[.]csv$", recursive = TRUE, full.names = TRUE)
summary_files <- list.files(ctx$input_dir, pattern = "summary[.]csv$", recursive = TRUE, full.names = TRUE)
plot_files <- list.files(ctx$input_dir, pattern = "[.](svg|png|jpg|jpeg)$", recursive = TRUE, full.names = TRUE, ignore.case = TRUE)

registries <- kflow_read_csv_union(registry_files)
summaries <- kflow_read_csv_union(summary_files)
utils::write.csv(registries, file.path(ctx$out_dir, "report-input-registry.csv"), row.names = FALSE)
utils::write.csv(summaries, file.path(ctx$out_dir, "report-input-summaries.csv"), row.names = FALSE)

plot_dir <- file.path(ctx$out_dir, "report-plots")
dir.create(plot_dir, recursive = TRUE, showWarnings = FALSE)
copied <- character()
for (index in seq_along(plot_files)) {
  target <- sprintf("plot-%03d%s", index, tools::file_ext(plot_files[index]))
  target <- sub("([0-9])([A-Za-z0-9]+)$", "\\1.\\2", target)
  file.copy(plot_files[index], file.path(plot_dir, target), overwrite = TRUE)
  copied <- c(copied, file.path("report-plots", target))
}

plot_markdown <- if (length(copied)) {
  paste(sprintf("### Plot %s\n\n![](%s)\n", seq_along(copied), copied), collapse = "\n")
} else {
  "No plot images were provided by upstream jobs."
}

title <- kflow_env("REPORT_TITLE", "BET 2026 Kflow report")
qmd <- c(
  "---",
  sprintf("title: \"%s\"", gsub("\"", "'", title)),
  "format:",
  "  html:",
  "    toc: true",
  "    embed-resources: true",
  "---",
  "",
  "## Overview",
  "",
  "This report was generated by a Kflow job from selected upstream model exploration outputs.",
  "",
  "## Input Registry",
  "",
  sprintf("Registry rows: `%s`.", nrow(registries)),
  "",
  "```{r}",
  "registry <- read.csv('report-input-registry.csv')",
  "if (nrow(registry)) print(utils::head(registry, 20)) else cat('No registry rows found.')",
  "```",
  "",
  "## Input Summaries",
  "",
  sprintf("Summary rows: `%s`.", nrow(summaries)),
  "",
  "```{r}",
  "summaries <- read.csv('report-input-summaries.csv')",
  "if (nrow(summaries)) print(utils::head(summaries, 20)) else cat('No summary rows found.')",
  "```",
  "",
  "## Plots",
  "",
  plot_markdown
)
writeLines(qmd, file.path(ctx$out_dir, "bet-kflow-report.qmd"))

if (nzchar(Sys.which("quarto"))) {
  old <- setwd(ctx$out_dir)
  on.exit(setwd(old), add = TRUE)
  status <- system2("quarto", c("render", "bet-kflow-report.qmd", "--to", "html", "--output", "bet-kflow-report.html"))
  if (!identical(status, 0L)) {
    stop("quarto render failed", call. = FALSE)
  }
} else {
  escape_html <- function(x) {
    x <- gsub("&", "&amp;", x, fixed = TRUE)
    x <- gsub("<", "&lt;", x, fixed = TRUE)
    x <- gsub(">", "&gt;", x, fixed = TRUE)
    x
  }
  html <- c(
    "<!doctype html>",
    "<html><body>",
    sprintf("<h1>%s</h1>", title),
    "<p>Quarto was not available in this runtime. The QMD source was still written.</p>",
    "<pre>",
    escape_html(paste(qmd, collapse = "\n")),
    "</pre>",
    "</body></html>"
  )
  writeLines(html, file.path(ctx$out_dir, "bet-kflow-report.html"))
}

report_summary <- data.frame(
  run_label = kflow_env("RUN_LABEL", ""),
  job_key = kflow_env("JOB_KEY", ""),
  registry_rows = nrow(registries),
  summary_rows = nrow(summaries),
  plot_files = length(copied),
  report_file = "bet-kflow-report.html",
  stringsAsFactors = FALSE
)
utils::write.csv(report_summary, file.path(ctx$out_dir, "report-summary.csv"), row.names = FALSE)
writeLines(capture.output(print(report_summary)), file.path(ctx$out_dir, "report-summary.txt"))
kflow_write_registry(ctx$out_dir, "report")
kflow_write_summary(ctx$out_dir, "report")
